# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cea3a1a6e2de0f43f310c5030ad496d82817ac92d2c92a91a731147b1049253964167a7f68af036b971328068e2bb0a70dfbfc5c9474478c86c4b9e762c304b3

test:
  secret_key_base: fec82922798d43d60b889d5b43bffdbb400a686c0b0e7a1bbe34e3531f13f1831cd8a1621ad94860466ccca86d4d30aa352af8475d6eaca349b2fb1c2212b969

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
